### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by iberis2** [iberis2/Todo-App#1]
### 만들고자 하는 기능이 무엇인가요?
Todo 생성기능

### 해당 기능 구현을 위해 할 일이 무엇인가요?
1. [ ] Todo App 틀 만들기
2. [ ]  API로 데이터 받아와서 CRUD 구현하기
3. [ ] Router 로 페이지 구분해서 다른 기능 추가하기

### 예상작업 시간
1 day
